### ISSUE TITLE
Autoscale not working as expected after deploying & using annotations

### ISSUE THREAD

**Issue by saleemmd5** [banzaicloud/hpa-operator#12]
Autoscale not working as expected after deploying & using annotations

we have used below annotations to test
cpu.hpa.autoscaling.banzaicloud.io/targetAverageUtilization: "1"
cpu.hpa.autoscaling.banzaicloud.io/targetAverageValue: "1"
memory.hpa.autoscaling.banzaicloud.io/targetAverageUtilization: "5"
seeing this `<unknown>/5%`   when we execute to see HPA
""""""""""""""
kubectl get hpa
NAME        REFERENCE              TARGETS        MINPODS   MAXPODS   REPLICAS   AGE
my-tomcat   Deployment/my-tomcat   <unknown>/5%   1         3         1          79m
"""""""""""""
seeing below logs in hap-autoscaler
```
time="2019-07-24T11:58:26Z" level=info msg="Autoscale annotations found on Deployment"
time="2019-07-24T11:58:26Z" level=info msg="HorizontalPodAutoscaler found, will be updated"
time="2019-07-24T11:58:26Z" level=info msg="number of metrics: 1"
time="2019-07-24T11:58:26Z" level=info msg="handle  : my-tomcat"```
no specific error other than this is seen

please suggest here.

**Comment by sancyx** [comment]
Hi @saleemmd5!  The hpa-operator is not responsible for scaling, only creates/updates hpa resource. The actual scale is done by hpa controller. It seems to me that in your case the hpa resoruce has been created, however it is not able to fetch metrics, which can have multiple causes: you should check you have a running metrics server and resource limits are set in your deployment. If you describe hpa `kubectl describe hpa` probably there more info about why hpa is not able to fetch metrics. Also cpu.hpa.autoscaling.banzaicloud.io/targetAverageUtilization: "1" seems to a me a bit low as hpa attempt to start as many replicas as needed to achieve an average cpu utilisation equal to 1%.

**Comment by saleemmd5** [comment]
`
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: missing request for cpu
Events:
  Type     Reason                        Age                  From                       Message
  ----     ------                        ----                 ----                       -------
  Warning  FailedGetResourceMetric       50m (x149 over 18h)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server is currently unable to handle the request (get pods.metrics.k8s.io)
  Warning  FailedComputeMetricsReplicas  35m (x45 over 46m)   horizontal-pod-autoscaler  failed to get cpu utilization: missing request for cpu
  Warning  FailedGetResourceMetric       11s (x179 over 46m)  horizontal-pod-autoscaler  missing request for cpu`
`kubectl top pods
NAME                         CPU(cores)   MEMORY(bytes)
my-tomcat-6f58cdfb86-bbd2v   2m           125Mi`
this is the output for hpa. and metric server looks fine for pulling metrics.

**Comment by sancyx** [comment]
The problem is in this case: "the HPA was unable to compute the replica count: missing request for cpu". The requested cpu resource need to be set for cpu in spec.containers[].resources.requests.cpu.
