### ISSUE TITLE
the server could not find the requested resource

### ISSUE THREAD

**Issue by shuoshadow** [banzaicloud/hpa-operator#15]
ERROR: logging before flag.Parse: E1107 07:41:58.905297       1 reflector.go:205] github.com/banzaicloud/hpa-operator/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer.go:80: Failed to list *unstructured.Unstructured: the server could not find the requested resource

**Comment by sancyx** [comment]
Hi @shuoshadow, this error look similar to this https://github.com/operator-framework/operator-sdk/issues/1858 it's coming from operatetor sdk. It's a bit strange since hpa-operator doesn't use any custom resource is only watching Deployments and Statefullsets. Could you please tell us the K8s version, also the version the operator and how did you installed the operator, chart version used etc. so that we can try to reproduce this error.

**Comment by shuoshadow** [comment]
> Hi @shuoshadow, this error look similar to this [operator-framework/operator-sdk#1858](https://github.com/operator-framework/operator-sdk/issues/1858) it's coming from operatetor sdk. It's a bit strange since hpa-operator doesn't use any custom resource is only watching Deployments and Statefullsets. Could you please tell us the K8s version, also the version the operator and how did you installed the operator, chart version used etc. so that we can try to reproduce this error.

hi， k8s version: v1.8.8
i install the operator with operator.yaml and rbac.yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hpa-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hpa-operator
  template:
    metadata:
      labels:
        name: hpa-operator
    spec:
      containers:
        - name: hpa-operator
          image: banzaicloud/hpa-operator:latest
          command:
          - hpa-operator
          imagePullPolicy: Always

**Comment by sancyx** [comment]
Could you please try `helm install banzaicloud-stable/hpa-operator` deploying the operator with this Helm chart https://github.com/banzaicloud/banzai-charts/tree/master/hpa-operator. Actually this is the recommended way to install, the yaml files are just an example, actually I had to update the docs, may be I will remove the yaml files.

**Comment by shuoshadow** [comment]
> Could you please try `helm install banzaicloud-stable/hpa-operator` deploying the operator with this Helm chart `https://github.com/banzaicloud/hpa-operator/tree/master/deploy/charts/hpa-operator`. Actually this is the recommended way to install, the yaml files are deprecated, I should remove them.

Thank you for your reply. I install in k8s version 1.14 and it‘s ok。Maybe the operator sdk problem
