### ISSUE TITLE
Object Metric is deprecated in kube metric adapter 

### ISSUE THREAD

**Issue by cindy52** [banzaicloud/hpa-operator#20]
**Is your feature request related to a problem? Please describe.**

Kube metrics adapter object metric is deprecated and most liked removed in the future
https://github.com/zalando-incubator/kube-metrics-adapter#example-object-metric-deprecated

**Describe the solution you'd like to see**

Use eternal metric instead
https://github.com/zalando-incubator/kube-metrics-adapter#example-external-metric
Change the annotation here to be `hpa.Annotations[fmt.Sprintf("metric-config.object.%s.prometheus/query", metricName)] = query`to be `metric-config.external.prometheus-query.prometheus/customMetrics`

**Describe alternatives you've considered**

**Additional context**

**Comment by sancyx** [comment]
Implemented in latest version: https://github.com/banzaicloud/hpa-operator/pull/24

**Comment by cindy52** [comment]
Close the issue accordingly ^^
