### ISSUE TITLE
Unfinished version pushed to Helm repo?

### ISSUE THREAD

**Issue by torjue** [banzaicloud/hpa-operator#23]
**Describe the bug**
It looks like someone pushed an unfinished version to the stable helm repo? Looks like the branch branch-v0.2. With this version you can no longer install the montor on clusters without the monitoring.coreos.com/v1 api.

**Steps to reproduce the issue:**
`helm install hpa-operator banzaicloud-stable/hpa-operator --set kube-metrics-adapter.enabled=false`

**Expected behavior**
Get the latest "stable" version, without requirement on monitoring.coreos.com/v1.

**Screenshots**
n/a

**Additional context**
Helm chart version 0.2.0. All works well when setting 0.1.0 as the specific version.

**Comment by sancyx** [comment]
Yes, it was released by mistake. You can try the new version [0.2.1](https://hub.helm.sh/charts/banzaicloud-stable/hpa-operator/0.2.1) where monitoring is disabled by default and installs the latest hpa-operator working with latest kube-metrics-adapter.

**Comment by torjue** [comment]
Thanks!
