### ISSUE TITLE
Use the official metrics server image

### ISSUE THREAD

**Issue by sagikazarmark** [banzaicloud/hpa-operator#33]
**Is your feature request related to a problem? Please describe.**
Metrics server doesn't have an official Helm chart. Bitnami's chart comes with their own, Debian based image.

There is an official metrics server image: `k8s.gcr.io/metrics-server/metrics-server:v0.4.1`

It's based on distroless, so it's more secure.

**Describe the solution you'd like to see**
Use the official image when installing the bitnami chart.

**Describe alternatives you've considered**
We also have a chart of our own (https://github.com/banzaicloud/banzai-charts/tree/master/metrics-server) but we decided to deprecate it recently. We could update it and go back to it.

Another alternative is to install the metrics server as a deployment in the HPA operator chart (using a config option)

**Additional context**
Ideally, the metrics server should not be installed by this chart at all, but in some places we still depend on it.

**Comment by sancyx** [comment]
This problem will be addressed here: https://github.com/banzaicloud/pipeline/issues/3396
