### ISSUE TITLE
[README.md] add helm repo add 

### ISSUE THREAD

**Issue by gaillard-corentin** [banzaicloud/hpa-operator#37]
Hi!
It's little complicate to find link to add your repo in helm, maybe, if you add this in your readme "helm repo add banzaicloud-stable https://github.com/banzaicloud/hpa-operator.git" more people use your project.

**Comment by sancyx** [comment]
bazaicloud-stable repo url is actually https://kubernetes-charts.banzaicloud.com, I've added to README.
