### ISSUE TITLE
Value for CPU and Percentage for memory

### ISSUE THREAD

**Issue by harshal-shah** [banzaicloud/hpa-operator#5]
Why is there support only for percentage values when specifying CPU and absolute value when specifying memory? 
The upstream API allows either of `targetAverageUtilization` and `targetAverageValue` to be used with CPU and Memory.

**Comment by sancyx** [comment]
The goal was to keep annotations as simple as possible, to avoid having complex annotation structure which allows specifying every supported combination, that's why we thought percentage for cpu and absolute for memory may be enough. However, may be we can simply just allow a '%' sign in value, meaning the values is `targetAverageUtilization` while if there's no '%' sign that would be a `targetAverageValue`?

**Comment by harshal-shah** [comment]
As of now the resource metric spec has only `targetAverageUtilization` and `targetAverageValue` so that sounds like a decent option. My only concern is, forgetting `%` sign is an easy mistake to make. 
Can we think of one additional annotation such as `autoscale/quantifier` (for the lack of an easier term) which can hold `targetAverageUtilization` or `targetAverageValue` or anything else which may be added in future? 

Also, It might be good to add a special label to the hpa resource so that if someone removes annotations from their deployment/statefulset, the controller can delete the hpa resource as well. (Maybe this should have its own issue)

**Comment by harshal-shah** [comment]
Yes, that seems like a much better option. ✅

**Comment by sancyx** [comment]
It appears name annotation you can't have more then one '/' so we have been further thinking about a correct structure of annotations, which would comply to K8s naming standards. The new structure would be something like below, where the first part of domain specifies the metrics type, while the part after the domain '/' will specify the values type in case of Resource metrics and name of the custom metric in case of Pod type metrics:

  cpu.hpa.autoscaling.banzaicloud.io/targetAverageUtilization: "70"  
  cpu.hpa.autoscaling.banzaicloud.io/targetAverageValue: "70"
  memory.hpa.autoscaling.banzaicloud.io/targetAverageValue: "1000Mi"
  memory.hpa.autoscaling.banzaicloud.io/targetAverageUtilization: "90"
  pod.hpa.autoscaling.banzaicloud.io/custom.metric.name: "1000Mi"

**Comment by harshal-shah** [comment]
Yes that seems good as well. Let me know once a new version is released with above fix and I will test it out.

**Comment by sancyx** [comment]
Fixes are available in version 0.1.3, you can also deploy it using it's helm chart: https://github.com/banzaicloud/banzai-charts/tree/master/hpa-operator
